//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamClient.Resources.Resx {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExamClient.Resources.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резервная копия.
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id опций:.
        /// </summary>
        internal static string Idопций {
            get {
                return ResourceManager.GetString("Idопций", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mail Пользователя:.
        /// </summary>
        internal static string MailПользователя {
            get {
                return ResourceManager.GetString("MailПользователя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор Авторизовался!.
        /// </summary>
        internal static string АдминистраторАвторизовался {
            get {
                return ResourceManager.GetString("АдминистраторАвторизовался", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Админская панель.
        /// </summary>
        internal static string Админскаяпанель {
            get {
                return ResourceManager.GetString("Админскаяпанель", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес:.
        /// </summary>
        internal static string Адрес {
            get {
                return ResourceManager.GetString("Адрес", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите адрес.
        /// </summary>
        internal static string Введитеадрес {
            get {
                return ResourceManager.GetString("Введитеадрес", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        internal static string ВведитеИмя {
            get {
                return ResourceManager.GetString("ВведитеИмя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        internal static string ВведитеПароль {
            get {
                return ResourceManager.GetString("ВведитеПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите порт.
        /// </summary>
        internal static string Введитепорт {
            get {
                return ResourceManager.GetString("Введитепорт", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите электронную почту.
        /// </summary>
        internal static string ВведитеЭлектроннуюПочту {
            get {
                return ResourceManager.GetString("ВведитеЭлектроннуюПочту", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ввели не почту!.
        /// </summary>
        internal static string Ввелинепочту {
            get {
                return ResourceManager.GetString("Ввелинепочту", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        internal static string Войти {
            get {
                return ResourceManager.GetString("Войти", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос.
        /// </summary>
        internal static string Вопрос {
            get {
                return ResourceManager.GetString("Вопрос", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопросы для теста:.
        /// </summary>
        internal static string Вопросыдлятеста {
            get {
                return ResourceManager.GetString("Вопросыдлятеста", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Востановить.
        /// </summary>
        internal static string Востановить {
            get {
                return ResourceManager.GetString("Востановить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Востановление успешно !.
        /// </summary>
        internal static string Востановлениеуспешно {
            get {
                return ResourceManager.GetString("Востановлениеуспешно", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход в учетную запись.
        /// </summary>
        internal static string ВходвучетнуюЗапись {
            get {
                return ResourceManager.GetString("ВходвучетнуюЗапись", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите Роль.
        /// </summary>
        internal static string ВыберитеРоль {
            get {
                return ResourceManager.GetString("ВыберитеРоль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор резервной копии.
        /// </summary>
        internal static string ВыборРезервнойКопии {
            get {
                return ResourceManager.GetString("ВыборРезервнойКопии", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор цвета:.
        /// </summary>
        internal static string Выборцвета {
            get {
                return ResourceManager.GetString("Выборцвета", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор экзамена.
        /// </summary>
        internal static string Выборэкзамена {
            get {
                return ResourceManager.GetString("Выборэкзамена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор языка:.
        /// </summary>
        internal static string Выборязыка {
            get {
                return ResourceManager.GetString("Выборязыка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранная роль:.
        /// </summary>
        internal static string Выбраннаяроль {
            get {
                return ResourceManager.GetString("Выбраннаяроль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный вопрос.
        /// </summary>
        internal static string Выбранныйвопрос {
            get {
                return ResourceManager.GetString("Выбранныйвопрос", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный ответ.
        /// </summary>
        internal static string Выбранныйответ {
            get {
                return ResourceManager.GetString("Выбранныйответ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный тест.
        /// </summary>
        internal static string Выбранныйтест {
            get {
                return ResourceManager.GetString("Выбранныйтест", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный экзамен.
        /// </summary>
        internal static string Выбранныйэкзамен {
            get {
                return ResourceManager.GetString("Выбранныйэкзамен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы зарегистрировались!.
        /// </summary>
        internal static string Вызарегистрировались {
            get {
                return ResourceManager.GetString("Вызарегистрировались", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не зарегистрировались!.
        /// </summary>
        internal static string Вынезарегистрировались {
            get {
                return ResourceManager.GetString("Вынезарегистрировались", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уже ответили на вопрос !.
        /// </summary>
        internal static string Выужеответилинавопрос {
            get {
                return ResourceManager.GetString("Выужеответилинавопрос", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уже сдали Тест!.
        /// </summary>
        internal static string ВыужесдалиТест {
            get {
                return ResourceManager.GetString("ВыужесдалиТест", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата регистрации:.
        /// </summary>
        internal static string Датарегистрации {
            get {
                return ResourceManager.GetString("Датарегистрации", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить вопрос.
        /// </summary>
        internal static string Добавитьвопрос {
            get {
                return ResourceManager.GetString("Добавитьвопрос", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить ответ.
        /// </summary>
        internal static string Добавитьответ {
            get {
                return ResourceManager.GetString("Добавитьответ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить тест.
        /// </summary>
        internal static string Добавитьтест {
            get {
                return ResourceManager.GetString("Добавитьтест", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить экзамен.
        /// </summary>
        internal static string Добавитьэкзамен {
            get {
                return ResourceManager.GetString("Добавитьэкзамен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Достижения.
        /// </summary>
        internal static string Достижения {
            get {
                return ResourceManager.GetString("Достижения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершен тест!.
        /// </summary>
        internal static string Завершентест {
            get {
                return ResourceManager.GetString("Завершентест", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закончить тест.
        /// </summary>
        internal static string Закончитьтест {
            get {
                return ResourceManager.GetString("Закончитьтест", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменения сохранены.
        /// </summary>
        internal static string Изменениясохранены {
            get {
                return ResourceManager.GetString("Изменениясохранены", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя/Вопрос:.
        /// </summary>
        internal static string ИмяИлиВопрос {
            get {
                return ResourceManager.GetString("ИмяИлиВопрос", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя/Ответ:.
        /// </summary>
        internal static string ИмяИлиОтвет {
            get {
                return ResourceManager.GetString("ИмяИлиОтвет", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя/Пользователя:.
        /// </summary>
        internal static string ИмяИлиПользователя {
            get {
                return ResourceManager.GetString("ИмяИлиПользователя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя/Теста:.
        /// </summary>
        internal static string ИмяИлиТеста {
            get {
                return ResourceManager.GetString("ИмяИлиТеста", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя/Экзамена:.
        /// </summary>
        internal static string ИмяИлиЭкзамена {
            get {
                return ResourceManager.GetString("ИмяИлиЭкзамена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя не заполнено.
        /// </summary>
        internal static string Имянезаполнено {
            get {
                return ResourceManager.GetString("Имянезаполнено", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя теста.
        /// </summary>
        internal static string Имятеста {
            get {
                return ResourceManager.GetString("Имятеста", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интерфейс администратора.
        /// </summary>
        internal static string ИнтерфейсАдминистратора {
            get {
                return ResourceManager.GetString("ИнтерфейсАдминистратора", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код вопроса (Id):.
        /// </summary>
        internal static string Кодвопроса {
            get {
                return ResourceManager.GetString("Кодвопроса", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код ответа (Id):.
        /// </summary>
        internal static string Кодответа {
            get {
                return ResourceManager.GetString("Кодответа", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код пользователя (Id):.
        /// </summary>
        internal static string Кодпользователя {
            get {
                return ResourceManager.GetString("Кодпользователя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код почты.
        /// </summary>
        internal static string КодПочты {
            get {
                return ResourceManager.GetString("КодПочты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код теста (Id):.
        /// </summary>
        internal static string Кодтеста {
            get {
                return ResourceManager.GetString("Кодтеста", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество вопросов :.
        /// </summary>
        internal static string Количествовопросов {
            get {
                return ResourceManager.GetString("Количествовопросов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        internal static string Логин {
            get {
                return ResourceManager.GetString("Логин", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        internal static string Назад {
            get {
                return ResourceManager.GetString("Назад", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование теста:.
        /// </summary>
        internal static string Наименованиетеста {
            get {
                return ResourceManager.GetString("Наименованиетеста", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование экзамена:.
        /// </summary>
        internal static string Наименованиеэкзамена {
            get {
                return ResourceManager.GetString("Наименованиеэкзамена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string Настройки {
            get {
                return ResourceManager.GetString("Настройки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать тест.
        /// </summary>
        internal static string Начатьтест {
            get {
                return ResourceManager.GetString("Начатьтест", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не заполнено разрешение!.
        /// </summary>
        internal static string Незаполненоразрешение {
            get {
                return ResourceManager.GetString("Незаполненоразрешение", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный адрес электронной почты!.
        /// </summary>
        internal static string Некорректныйадресэлектроннойпочты {
            get {
                return ResourceManager.GetString("Некорректныйадресэлектроннойпочты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный формат адреса электронной почты!.
        /// </summary>
        internal static string Некорректныйформатадресаэлектроннойпочты {
            get {
                return ResourceManager.GetString("Некорректныйформатадресаэлектроннойпочты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ок.
        /// </summary>
        internal static string Ок {
            get {
                return ResourceManager.GetString("Ок", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание ответа:.
        /// </summary>
        internal static string Описаниеответа {
            get {
                return ResourceManager.GetString("Описаниеответа", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ.
        /// </summary>
        internal static string Ответ {
            get {
                return ResourceManager.GetString("Ответ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответили не на все вопросы !.
        /// </summary>
        internal static string Ответилиненавсевопросы {
            get {
                return ResourceManager.GetString("Ответилиненавсевопросы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответы.
        /// </summary>
        internal static string Ответы {
            get {
                return ResourceManager.GetString("Ответы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответы для вопроса:.
        /// </summary>
        internal static string Ответыдлявопроса {
            get {
                return ResourceManager.GetString("Ответыдлявопроса", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответьте на вопрос:.
        /// </summary>
        internal static string Ответьтенавопрос {
            get {
                return ResourceManager.GetString("Ответьтенавопрос", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string Отмена {
            get {
                return ResourceManager.GetString("Отмена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценка.
        /// </summary>
        internal static string Оценка {
            get {
                return ResourceManager.GetString("Оценка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценка вопроса:.
        /// </summary>
        internal static string Оценкавопроса {
            get {
                return ResourceManager.GetString("Оценкавопроса", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Ошибка {
            get {
                return ResourceManager.GetString("Ошибка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка ответ!.
        /// </summary>
        internal static string Ошибкаответ {
            get {
                return ResourceManager.GetString("Ошибкаответ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка перехода на вопрос создать!.
        /// </summary>
        internal static string Ошибкапереходанавопроссоздать {
            get {
                return ResourceManager.GetString("Ошибкапереходанавопроссоздать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания!.
        /// </summary>
        internal static string Ошибкасоздания {
            get {
                return ResourceManager.GetString("Ошибкасоздания", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль:.
        /// </summary>
        internal static string Пароли {
            get {
                return ResourceManager.GetString("Пароли", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль:.
        /// </summary>
        internal static string Пароль {
            get {
                return ResourceManager.GetString("Пароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль введен не верно!.
        /// </summary>
        internal static string Парольвведенневерно {
            get {
                return ResourceManager.GetString("Парольвведенневерно", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль на подтверждение не заполнен!.
        /// </summary>
        internal static string Парольнаподтверждениенезаполнен {
            get {
                return ResourceManager.GetString("Парольнаподтверждениенезаполнен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль не заполнен!.
        /// </summary>
        internal static string Парольнезаполнен {
            get {
                return ResourceManager.GetString("Парольнезаполнен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перечень вопросов.
        /// </summary>
        internal static string Переченьвопросов {
            get {
                return ResourceManager.GetString("Переченьвопросов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перечень ответов.
        /// </summary>
        internal static string Переченьответов {
            get {
                return ResourceManager.GetString("Переченьответов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перечень тестов.
        /// </summary>
        internal static string Переченьтестов {
            get {
                return ResourceManager.GetString("Переченьтестов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перечень экзаменов.
        /// </summary>
        internal static string Переченьэкзаменов {
            get {
                return ResourceManager.GetString("Переченьэкзаменов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        internal static string Пользователь {
            get {
                return ResourceManager.GetString("Пользователь", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь Авторизовался!.
        /// </summary>
        internal static string ПользовательАвторизовался {
            get {
                return ResourceManager.GetString("ПользовательАвторизовался", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помощь:.
        /// </summary>
        internal static string Помощь {
            get {
                return ResourceManager.GetString("Помощь", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт.
        /// </summary>
        internal static string Порт {
            get {
                return ResourceManager.GetString("Порт", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почта не заполнена!.
        /// </summary>
        internal static string Почтанезаполнена {
            get {
                return ResourceManager.GetString("Почтанезаполнена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почта не пустая!.
        /// </summary>
        internal static string Почтанепустая {
            get {
                return ResourceManager.GetString("Почтанепустая", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правильные ответы:.
        /// </summary>
        internal static string Правильныеответы {
            get {
                return ResourceManager.GetString("Правильныеответы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right answer:.
        /// </summary>
        internal static string Правильныйответ {
            get {
                return ResourceManager.GetString("Правильныйответ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка:.
        /// </summary>
        internal static string Произошлаошибка {
            get {
                return ResourceManager.GetString("Произошлаошибка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        internal static string Регистрация {
            get {
                return ResourceManager.GetString("Регистрация", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        internal static string Редактировать {
            get {
                return ResourceManager.GetString("Редактировать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резевная копия создалась !.
        /// </summary>
        internal static string Резевнаякопиясоздалась {
            get {
                return ResourceManager.GetString("Резевнаякопиясоздалась", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резервная копия.
        /// </summary>
        internal static string РезервнаяКопия {
            get {
                return ResourceManager.GetString("РезервнаяКопия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ролей нет!.
        /// </summary>
        internal static string Ролейнет {
            get {
                return ResourceManager.GetString("Ролейнет", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роль пользователя.
        /// </summary>
        internal static string Рольпользователя {
            get {
                return ResourceManager.GetString("Рольпользователя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер выключен или недоступен!.
        /// </summary>
        internal static string Сервервыключенилинедоступен {
            get {
                return ResourceManager.GetString("Сервервыключенилинедоступен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        internal static string Создать {
            get {
                return ResourceManager.GetString("Создать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать вопрос.
        /// </summary>
        internal static string Создатьвопрос {
            get {
                return ResourceManager.GetString("Создатьвопрос", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать пользователя.
        /// </summary>
        internal static string СоздатьПользователя {
            get {
                return ResourceManager.GetString("СоздатьПользователя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать тест.
        /// </summary>
        internal static string Создатьтест {
            get {
                return ResourceManager.GetString("Создатьтест", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать экзамен.
        /// </summary>
        internal static string Создатьэкзамен {
            get {
                return ResourceManager.GetString("Создатьэкзамен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение.
        /// </summary>
        internal static string Сообщение {
            get {
                return ResourceManager.GetString("Сообщение", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранен тест!.
        /// </summary>
        internal static string Сохранентест {
            get {
                return ResourceManager.GetString("Сохранентест", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string Сохранить {
            get {
                return ResourceManager.GetString("Сохранить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник вопросов.
        /// </summary>
        internal static string Справочник_вопросов {
            get {
                return ResourceManager.GetString("Справочник вопросов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник тестов.
        /// </summary>
        internal static string Справочник_тестов {
            get {
                return ResourceManager.GetString("Справочник тестов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник вопросов.
        /// </summary>
        internal static string СправочникВопросов {
            get {
                return ResourceManager.GetString("СправочникВопросов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник ответов.
        /// </summary>
        internal static string СправочникОтветов {
            get {
                return ResourceManager.GetString("СправочникОтветов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник пользователей.
        /// </summary>
        internal static string СправочникПользователей {
            get {
                return ResourceManager.GetString("СправочникПользователей", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник тестов.
        /// </summary>
        internal static string СправочникТестов {
            get {
                return ResourceManager.GetString("СправочникТестов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник экзаменов.
        /// </summary>
        internal static string СправочникЭкзаменов {
            get {
                return ResourceManager.GetString("СправочникЭкзаменов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика.
        /// </summary>
        internal static string Статистика {
            get {
                return ResourceManager.GetString("Статистика", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика экзаменов.
        /// </summary>
        internal static string Статистикаэкзаменов {
            get {
                return ResourceManager.GetString("Статистикаэкзаменов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такого пользователя нет!.
        /// </summary>
        internal static string Такогопользователянет {
            get {
                return ResourceManager.GetString("Такогопользователянет", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст вопроса:.
        /// </summary>
        internal static string Текствопроса {
            get {
                return ResourceManager.GetString("Текствопроса", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест.
        /// </summary>
        internal static string Тест {
            get {
                return ResourceManager.GetString("Тест", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест не завершен!.
        /// </summary>
        internal static string Тестнезавершен {
            get {
                return ResourceManager.GetString("Тестнезавершен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тестовые вопросы с ответами.
        /// </summary>
        internal static string Тестовыевопросысответами {
            get {
                return ResourceManager.GetString("Тестовыевопросысответами", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тесты для экзамена:.
        /// </summary>
        internal static string Тестыдляэкзамена {
            get {
                return ResourceManager.GetString("Тестыдляэкзамена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тесты из вопросов.
        /// </summary>
        internal static string Тестыизвопросов {
            get {
                return ResourceManager.GetString("Тестыизвопросов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомление.
        /// </summary>
        internal static string Уведомление {
            get {
                return ResourceManager.GetString("Уведомление", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string Удалить {
            get {
                return ResourceManager.GetString("Удалить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаляется вопрос.
        /// </summary>
        internal static string Удаляетсявопрос {
            get {
                return ResourceManager.GetString("Удаляетсявопрос", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаляется ответ.
        /// </summary>
        internal static string Удаляетсяответ {
            get {
                return ResourceManager.GetString("Удаляетсяответ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаляется тест.
        /// </summary>
        internal static string Удаляетсятест {
            get {
                return ResourceManager.GetString("Удаляетсятест", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экзамен.
        /// </summary>
        internal static string Экзамен {
            get {
                return ResourceManager.GetString("Экзамен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экзамены для пользователя:.
        /// </summary>
        internal static string Экзаменыдляпользователя {
            get {
                return ResourceManager.GetString("Экзаменыдляпользователя", resourceCulture);
            }
        }
    }
}
