<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" VersionOverride="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Primitives" VersionOverride="8.0.0" />
    <PackageReference Include="System.Drawing.Common" VersionOverride="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExamModels\ExamModels.csproj" />
  </ItemGroup>
</Project>