<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ExamWorkerService-e8344981-06b5-4971-9bb0-89715330f9e3</UserSecretsId>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Microsoft.Extensions.Primitives" VersionOverride="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" VersionOverride="9.0.6" />
    <PackageReference Include="System.Drawing.Common" VersionOverride="9.0.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExamServer\ExamServer.csproj" />
  </ItemGroup>
</Project>